import type { RuleScenario, Rule10Params } from '../types.ts'
import type { BoatState, SceneState } from '$lib/canvas/types.ts'
import {
  DEFAULT_WORLD,
  DEFAULT_WIND_DIR_DEG,
  DEFAULT_WIND_SPEED_KNOTS,
  startPosition,
  generateLinearKeyframes,
  wrapClip,
  deriveTack,
  normalize360,
} from './utils.ts'

/**
 * On opposite tacks: port-tack boat keeps clear of starboard-tack boat.
 * Generated by retreating both boats backward from a shared crossing point so
 * they converge there at `timeToConflictSec`.
 */
export function generateRule10Scenario(params: Rule10Params = {}): RuleScenario {
  const wind = params.windDirDeg ?? DEFAULT_WIND_DIR_DEG
  const world = params.worldSize ?? DEFAULT_WORLD
  const speed = params.speedKnots ?? 6
  const tToC = params.timeToConflictSec ?? 6
  const duration = params.durationSec ?? tToC + 1.5
  const cross = params.crossingPoint ?? { x: world.x / 2, y: world.y / 2 }

  // Default headings: close-hauled on each tack.
  // Starboard tack heads ~135° relative to wind-from (i.e. wind on stbd bow);
  // port tack heads ~-135° (225° relative to wind-from).
  // Headings go FROM wind direction. wind=0 → stbd=315°(NW), port=45°(NE).
  const stbdHeading = normalize360(params.stbdHeadingDeg ?? wind - 45)
  const portHeading = normalize360(params.portHeadingDeg ?? wind + 45)

  const boatAId = params.boatAId ?? 'boat-stbd'
  const boatBId = params.boatBId ?? 'boat-port'

  const stbdStart = startPosition(cross, stbdHeading, speed, tToC)
  const portStart = startPosition(cross, portHeading, speed, tToC)

  const boats: BoatState[] = [
    {
      id: boatAId,
      position: stbdStart,
      heading: stbdHeading,
      speed,
      hullColor: 'maize',
      sailColor: 'blue',
      label: 'Boat A',
      isPlayer: false,
    },
    {
      id: boatBId,
      position: portStart,
      heading: portHeading,
      speed,
      hullColor: 'orange',
      sailColor: 'white',
      label: 'Boat B',
      isPlayer: false,
    },
  ]

  const scene: SceneState = {
    worldSize: world,
    wind: { directionDeg: wind, speedKnots: DEFAULT_WIND_SPEED_KNOTS },
    marks: [],
    boats,
    display: {
      showLabels: true,
      showWake: true,
      showWindStreaks: true,
      showWindIndicator: true,
      showGrid: false,
    },
  }

  const keyframes = generateLinearKeyframes(
    [
      { id: boatAId, startPos: stbdStart, headingDeg: stbdHeading, speedKnots: speed },
      { id: boatBId, startPos: portStart, headingDeg: portHeading, speedKnots: speed },
    ],
    duration,
  )

  // The port-tack boat must keep clear.
  const keepClearId = deriveTack(stbdHeading, wind) === 'port' ? boatAId : boatBId
  const keepClearLabel = keepClearId === boatAId ? 'Boat A' : 'Boat B'
  const rightOfWayLabel = keepClearId === boatAId ? 'Boat B' : 'Boat A'

  return {
    id: `r10-w${Math.round(wind)}-t${tToC}`,
    title: 'Port-Starboard Crossing',
    questionText: 'Two boats are converging. Click the boat that must keep clear.',
    questionType: 'who_must_keep_clear',
    primaryRuleId: 'rule_10',
    scene,
    animation: wrapClip(keyframes, duration, true),
    answer: {
      boatId: keepClearId,
      explanation: `${keepClearLabel} is on port tack (wind on the boat's left side). Under Rule 10, a port-tack boat must keep clear of a starboard-tack boat. ${rightOfWayLabel} on starboard tack has right of way.`,
      ruleRef: 'rule_10',
    },
    difficulty: 'beginner',
    tags: ['upwind', 'crossing'],
  }
}
